-- Model: clusters. The question the trader asks.
--
-- Buyer       owners named on one filing report as a group, so they act as one.
--             ~ = the equivalence relation generated by "named on the same filing";
--             a buyer is a class of ~, i.e. a connected component of the co-filing graph,
--             labelled by its smallest owner CIK.
--
-- Purchase    a line with code P, with its company and each buyer on its filing.
--
-- buyers(c, d, w) = |{ buyer b : b bought c's stock on a day in [d − w + 1, d] }|
--             evaluated at every purchase date d: buyers only rises on a purchase
--             date, so its maximum is always reached on one.
--
-- clusters(w, k) = companies with some d where buyers(c, d, w) ≥ k,
--             ranked by their largest count, then by the most recent such d.
--
-- Flag        one_day_one_price: every purchase in every cluster window shares one
--             date and one price. Distinct insiders buying on one day at one price
--             to the cent is likely a company-run programme, not independent
--             conviction (5 Bank Bradesco officers, 18 Sep, all at $17.98).
--             Flagged, not excluded: the trader decides.

CREATE VIEW buyer_of AS
WITH RECURSIVE
    edges AS (
        SELECT a.owner_cik AS x, b.owner_cik AS y
        FROM owners a JOIN owners b USING (accession)
    ),
    reach (x, y) AS (
        SELECT x, y FROM edges
        UNION
        SELECT r.x, e.y FROM reach r JOIN edges e ON r.y = e.x
    )
SELECT x AS owner_cik, min(y) AS buyer
FROM reach
GROUP BY x;

-- One row per (purchase line, owner on its filing). A line repeats once per
-- owner; buyers() counts distinct buyers, so the repeats cannot change it.
CREATE VIEW purchases AS
SELECT f.issuer_cik AS cik, l.traded, l.price, b.buyer
FROM lines l
JOIN filings f USING (accession)
JOIN owners o USING (accession)
JOIN buyer_of b USING (owner_cik)
WHERE l.code = 'P';

CREATE MACRO buyers(w) AS TABLE
SELECT d.cik, d.traded AS d, count(DISTINCT p.buyer) AS buyers,
       count(DISTINCT (p.traded, p.price)) = 1 AS one_day_one_price
FROM (SELECT DISTINCT cik, traded FROM purchases) d
JOIN purchases p ON p.cik = d.cik AND p.traded BETWEEN d.traded - (w - 1) AND d.traded
GROUP BY d.cik, d.traded;

CREATE MACRO clusters(w, k) AS TABLE
SELECT c.ticker, c.name, max(b.buyers) AS peak_buyers, max(b.d) AS latest_cluster,
       bool_and(b.one_day_one_price) AS one_day_one_price
FROM buyers(w) b
JOIN companies c USING (cik)
WHERE b.buyers >= k
GROUP BY c.cik, c.ticker, c.name
ORDER BY peak_buyers DESC, latest_cluster DESC;
